window.__MANIFEST__ = {
  "title": "Medical Obstetric Disorders",
  "version": "1.0",
  "topics": [
    {
      "type": "heading",
      "title": "Obstetric",
      "icon": "🩺",
      "description": "Medical Obstetric Disorders — Complete Slide Deck"
    },
    {
      "id": "3a_Hemorrhage_Coagulation",
      "title": "3a — Hemorrhage & Coagulation",
      "description": "Antepartum hemorrhage and disseminated intravascular coagulopathy",
      "icon": "🩸",
      "folder": "3a_Hemorrhage_Coagulation",
      "slidesPath": "3a_Hemorrhage_Coagulation/slides",
      "slideCount": 31,
      "slides": [
        "slide-01.html", "slide-02.html", "slide-03.html", "slide-04.html", "slide-05.html",
        "slide-06.html", "slide-07.html", "slide-08.html", "slide-09.html", "slide-10.html",
        "slide-11.html", "slide-12.html", "slide-13.html", "slide-14.html", "slide-15.html",
        "slide-16.html", "slide-17.html", "slide-18.html", "slide-19.html", "slide-20.html",
        "slide-21.html", "slide-22.html", "slide-23.html", "slide-24.html", "slide-25.html",
        "slide-26.html", "slide-27.html", "slide-28.html", "slide-29.html", "slide-30.html",
        "slide-31.html"
      ],
      "slideTitles": [
        "Hemorrhage & Coagulation — Cover",
        "Slide 02",
        "Slide 03",
        "Slide 04",
        "Slide 05",
        "Slide 06",
        "Slide 07",
        "Slide 08",
        "Slide 09",
        "Slide 10",
        "Slide 11",
        "Slide 12",
        "Slide 13",
        "Slide 14",
        "Slide 15",
        "Slide 16",
        "Slide 17",
        "Slide 18",
        "Slide 19",
        "Slide 20",
        "Slide 21",
        "Slide 22",
        "Slide 23",
        "Slide 24",
        "Slide 25",
        "Slide 26",
        "Slide 27",
        "Slide 28",
        "Slide 29",
        "Slide 30",
        "Slide 31"
      ]
    },
    {
      "id": "3b_Medical_Diseases",
      "title": "3b — Medical Diseases",
      "description": "Vomiting, anemia, cardiac disease, hypertension, diabetes, UTI, and thromboembolism in pregnancy",
      "icon": "🏥",
      "folder": "3b_Medical_Diseases",
      "slidesPath": "3b_Medical_Diseases/slides",
      "slideCount": 74,
      "slides": [
        "slide-01.html", "slide-02.html", "slide-03.html", "slide-04.html", "slide-05.html",
        "slide-06.html", "slide-07.html", "slide-08.html", "slide-09.html", "slide-10.html",
        "slide-11.html", "slide-12.html", "slide-13.html", "slide-14.html", "slide-15.html",
        "slide-16.html", "slide-17.html", "slide-18.html", "slide-19.html", "slide-20.html",
        "slide-21.html", "slide-22.html", "slide-23.html", "slide-24.html", "slide-25.html",
        "slide-26.html", "slide-27.html", "slide-28.html", "slide-29.html", "slide-30.html",
        "slide-31.html", "slide-32.html", "slide-33.html", "slide-34.html", "slide-35.html",
        "slide-36.html", "slide-37.html", "slide-38.html", "slide-39.html", "slide-40.html",
        "slide-41.html", "slide-42.html", "slide-43.html", "slide-44.html", "slide-45.html",
        "slide-46.html", "slide-47.html", "slide-48.html", "slide-49.html", "slide-50.html",
        "slide-51.html", "slide-52.html", "slide-53.html", "slide-54.html", "slide-55.html",
        "slide-56.html", "slide-57.html", "slide-58.html", "slide-59.html", "slide-60.html",
        "slide-61.html", "slide-62.html", "slide-63.html", "slide-64.html", "slide-65.html",
        "slide-66.html", "slide-67.html", "slide-68.html", "slide-69.html", "slide-70.html",
        "slide-71.html", "slide-72.html", "slide-73.html", "slide-74.html"
      ],
      "slideTitles": [
        "Medical Diseases — Cover",
        "Slide 02",
        "Slide 03",
        "Slide 04",
        "Slide 05",
        "Slide 06",
        "Slide 07",
        "Slide 08",
        "Slide 09",
        "Slide 10",
        "Slide 11",
        "Slide 12",
        "Slide 13",
        "Slide 14",
        "Slide 15",
        "Slide 16",
        "Slide 17",
        "Slide 18",
        "Slide 19",
        "Slide 20",
        "Slide 21",
        "Slide 22",
        "Slide 23",
        "Slide 24",
        "Slide 25",
        "Slide 26",
        "Slide 27",
        "Slide 28",
        "Slide 29",
        "Slide 30",
        "Slide 31",
        "Slide 32",
        "Slide 33",
        "Slide 34",
        "Slide 35",
        "Slide 36",
        "Slide 37",
        "Slide 38",
        "Slide 39",
        "Slide 40",
        "Slide 41",
        "Slide 42",
        "Slide 43",
        "Slide 44",
        "Slide 45",
        "Slide 46",
        "Slide 47",
        "Slide 48",
        "Slide 49",
        "Slide 50",
        "Slide 51",
        "Slide 52",
        "Slide 53",
        "Slide 54",
        "Slide 55",
        "Slide 56",
        "Slide 57",
        "Slide 58",
        "Slide 59",
        "Slide 60",
        "Slide 61",
        "Slide 62",
        "Slide 63",
        "Slide 64",
        "Slide 65",
        "Slide 66",
        "Slide 67",
        "Slide 68",
        "Slide 69",
        "Slide 70",
        "Slide 71",
        "Slide 72",
        "Slide 73",
        "Slide 74"
      ]
    },
    {
      "id": "3c_Infections_Immunological",
      "title": "3c — Infections & Immunological",
      "description": "Infectious diseases in pregnancy and RH incompatibility",
      "icon": "🔬",
      "folder": "3c_Infections_Immunological",
      "slidesPath": "3c_Infections_Immunological/slides",
      "slideCount": 26,
      "slides": [
        "slide-01.html", "slide-02.html", "slide-03.html", "slide-04.html", "slide-05.html",
        "slide-06.html", "slide-07.html", "slide-08.html", "slide-09.html", "slide-10.html",
        "slide-11.html", "slide-12.html", "slide-13.html", "slide-14.html", "slide-15.html",
        "slide-16.html", "slide-17.html", "slide-18.html", "slide-19.html", "slide-20.html",
        "slide-21.html", "slide-22.html", "slide-23.html", "slide-24.html", "slide-25.html",
        "slide-26.html"
      ],
      "slideTitles": [
        "Infections & Immunological — Cover",
        "Slide 02",
        "Slide 03",
        "Slide 04",
        "Slide 05",
        "Slide 06",
        "Slide 07",
        "Slide 08",
        "Slide 09",
        "Slide 10",
        "Slide 11",
        "Slide 12",
        "Slide 13",
        "Slide 14",
        "Slide 15",
        "Slide 16",
        "Slide 17",
        "Slide 18",
        "Slide 19",
        "Slide 20",
        "Slide 21",
        "Slide 22",
        "Slide 23",
        "Slide 24",
        "Slide 25",
        "Slide 26"
      ]
    },
    {
      "id": "3d_Multiple_Pregnancy_Preterm",
      "title": "3d — Multiple Pregnancy & Preterm",
      "description": "Multiple pregnancy, preterm labor, and premature rupture of membranes",
      "icon": "👶",
      "folder": "3d_Multiple_Pregnancy_Preterm",
      "slidesPath": "3d_Multiple_Pregnancy_Preterm/slides",
      "slideCount": 22,
      "slides": [
        "slide-01.html", "slide-02.html", "slide-03.html", "slide-04.html", "slide-05.html",
        "slide-06.html", "slide-07.html", "slide-08.html", "slide-09.html", "slide-10.html",
        "slide-11.html", "slide-12.html", "slide-13.html", "slide-14.html", "slide-15.html",
        "slide-16.html", "slide-17.html", "slide-18.html", "slide-19.html", "slide-20.html",
        "slide-21.html", "slide-22.html"
      ],
      "slideTitles": [
        "Multiple Pregnancy & Preterm — Cover",
        "Slide 02",
        "Slide 03",
        "Slide 04",
        "Slide 05",
        "Slide 06",
        "Slide 07",
        "Slide 08",
        "Slide 09",
        "Slide 10",
        "Slide 11",
        "Slide 12",
        "Slide 13",
        "Slide 14",
        "Slide 15",
        "Slide 16",
        "Slide 17",
        "Slide 18",
        "Slide 19",
        "Slide 20",
        "Slide 21",
        "Slide 22"
      ]
    },
    {
      "id": "3e_Fetal_Complications",
      "title": "3e — Fetal Complications",
      "description": "Amniotic fluid abnormalities, IUGR, postterm pregnancy, macrosomia, intrauterine fetal death, and birth injuries",
      "icon": "🩺",
      "folder": "3e_Fetal_Complications",
      "slidesPath": "3e_Fetal_Complications/slides",
      "slideCount": 38,
      "slides": [
        "slide-01.html", "slide-02.html", "slide-03.html", "slide-04.html", "slide-05.html",
        "slide-06.html", "slide-07.html", "slide-08.html", "slide-09.html", "slide-10.html",
        "slide-11.html", "slide-12.html", "slide-13.html", "slide-14.html", "slide-15.html",
        "slide-16.html", "slide-17.html", "slide-18.html", "slide-19.html", "slide-20.html",
        "slide-21.html", "slide-22.html", "slide-23.html", "slide-24.html", "slide-25.html",
        "slide-26.html", "slide-27.html", "slide-28.html", "slide-29.html", "slide-30.html",
        "slide-31.html", "slide-32.html", "slide-33.html", "slide-34.html", "slide-35.html",
        "slide-36.html", "slide-37.html", "slide-38.html"
      ],
      "slideTitles": [
        "Fetal Complications — Cover",
        "Slide 02",
        "Slide 03",
        "Slide 04",
        "Slide 05",
        "Slide 06",
        "Slide 07",
        "Slide 08",
        "Slide 09",
        "Slide 10",
        "Slide 11",
        "Slide 12",
        "Slide 13",
        "Slide 14",
        "Slide 15",
        "Slide 16",
        "Slide 17",
        "Slide 18",
        "Slide 19",
        "Slide 20",
        "Slide 21",
        "Slide 22",
        "Slide 23",
        "Slide 24",
        "Slide 25",
        "Slide 26",
        "Slide 27",
        "Slide 28",
        "Slide 29",
        "Slide 30",
        "Slide 31",
        "Slide 32",
        "Slide 33",
        "Slide 34",
        "Slide 35",
        "Slide 36",
        "Slide 37",
        "Slide 38"
      ]
    }
  ],
  "totalTopics": 5,
  "totalSlides": 191
};
